### ISSUE TITLE
[Bug] Twitter UserId should be bigInt

### ISSUE THREAD

**Issue by hourone-bi** [fivetran/dbt_twitter_organic_source#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In model **stg_twitter_organic__tweet** - the **user_id** column is type casted to int. Our twitter user ID is bigint - which means that the model creation fails with "**int out of range**". 
Should keep the **user_id** as a bigint - it will solve the issue:

So instead of 
`        cast(user_id as {{ dbt_utils.type_int() }}) as user_id,`
do:
` user_id,`

### Relevant error log or model output

```shell
int out of range
```

### Expected behavior

Model build should pass successfully.

### dbt Project configurations

Not relevant

### Package versions

latest

### What database are you using dbt with?

postgres

### dbt Version

1.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @hourone-bi! Thanks so much for opening this issue.

That is interesting that you are experiencing this issue as I wouldn't have imagined this field to be a bigint value. Unfortunately, we do still want to cast this field to ensure consistency across the various data warehouses. I wonder if leveraging the bigint macro (seen below) will correct this issue. 

https://github.com/dbt-labs/dbt-utils/blob/ae6e1b43e6c57ec8afbd550236a1d59ec668df4e/macros/cross_db_utils/datatypes.sql#L73-L85

I see you would be open to creating a PR. If you would like to make the adjustment within the model to use `{{ dbt_utils.type_bigint() }}` instead of the standard int.
https://github.com/fivetran/dbt_twitter_organic_source/blob/8f84f7533aa78b94ef8a0be9b59209a088a64154/models/stg_twitter_organic__tweet.sql#L54

Let me know if you would like to tackle this PR!

**Comment by hourone-bi** [comment]
Hey Joe,

Thank you for handling this so quickly. I've did a quick check.
When you replace:
cast(user_id as {{ dbt_utils.type_int() }}) as user_id,
With this line:
cast(user_id as {{ dbt_utils.type_bigint() }}) as user_id,

It will work perfectly.

I'd appreciate it if you can handle the pull request.
Please let me know once an updated version is released - so I can add
twitter back.

Best,
Lior Ash

**Comment by hourone-bi** [comment]
Hey. Any updates? would be great if this change can be committed...
Best.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @hourone-bi, I apologize for the delay. The PR above is open and we are planning to get it merged by the end of the day!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @hourone-bi the latest release of the package addresses this issue. You should be good to go now!

**Comment by liorash** [comment]
Amazing - Thank you so much for the quick response and fix! 
You're the best.
Lior
